// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Tabbar: typeof import('./src/components/Tabbar/index.vue')['default'];
    VanActionSheet: typeof import('vant/es')['ActionSheet'];
    VanCellGroup: typeof import('vant/es')['CellGroup'];
    VanConfigProvider: typeof import('vant/es')['ConfigProvider'];
    VanField: typeof import('vant/es')['Field'];
    VanNavBar: typeof import('vant/es')['NavBar'];
    VanSwitch: typeof import('vant/es')['Switch'];
    VanTabbar: typeof import('vant/es')['Tabbar'];
    VanTabbarItem: typeof import('vant/es')['TabbarItem'];
  }
}
